[package]
name = "rust-postgres-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
deadpool-postgres = "0.14"
once_cell = "1"
thiserror = "1"
dotenvy = "0.15.7"
dirs = "5.0"